In [456]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

In [802]:
df=pd.read_excel('./../myproj/Survey.xlsx',nrows=830)

df=df.loc[df['Which age group you belong to?']==2]
#df=df.loc[df['Level Of Anxiety ']!=3]
df=df.loc[df['Have you felt frustrated by having your activities, major life events or opportunities affected by the virus? ']!=1]
df=df.loc[df['Do you feel like you have wasted your time during the lock down or have you ever felt pressurized by your peer’s accomplishments during the lock down?']!=0]
df.shape

(55, 39)

In [963]:
X=df[[
       'Have you ever felt afraid or anxious to go to hospital during this pandemic?',
      ]]

In [964]:
y=df['Level Of Anxiety ']
y.unique()

array([2, 1, 0], dtype=int64)

In [965]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [966]:
regressor = DecisionTreeClassifier(random_state = 0) 
# fit the regressor with X and Y data 
regressor.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [967]:
y_pred = regressor.predict(X_test)
y_pred = [int(x) for x in y_pred]

In [968]:
y_pred

[0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1]

In [969]:
y_actual=[3 if x>=15 else 2 if x>=10 else 1 if x>=5 else 0 for x in y_test]

In [970]:
y_test

727    0
443    0
567    0
307    1
80     0
18     0
429    0
640    1
749    0
400    2
28     1
Name: Level Of Anxiety , dtype: int64

In [971]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6363636363636364

In [972]:
regressor.feature_importances_

array([1.])

In [973]:
df=pd.read_excel('./../myproj/Survey.xlsx',nrows=830)

df=df.loc[df['Which age group you belong to?']==2]
#df=df.loc[df['Level Of Anxiety ']!=3]
df=df.loc[df['Have you felt frustrated by having your activities, major life events or opportunities affected by the virus? ']!=1]
df=df.loc[df['Do you feel like you have wasted your time during the lock down or have you ever felt pressurized by your peer’s accomplishments during the lock down?']!=1]
df.shape

(104, 39)

In [974]:
X=df[[
       'What is your gender?',
       'Have you been affected by not being able to visit religious places?',
       'Do you miss hanging out with people outside of your house?',
       
      ]]

In [975]:
y=df['Level Of Anxiety ']
y.unique()

array([0, 1], dtype=int64)

In [976]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [977]:
regressor = DecisionTreeClassifier(random_state = 0) 
# fit the regressor with X and Y data 
regressor.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [978]:
y_pred = regressor.predict(X_test)
y_pred = [int(x) for x in y_pred]

In [979]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.75

In [980]:
regressor.feature_importances_

array([0.40269086, 0.35472585, 0.24258329])

In [981]:
df=pd.read_excel('./../myproj/Survey.xlsx',nrows=830)

df=df.loc[df['Which age group you belong to?']==2]
#df=df.loc[df['Level Of Anxiety ']!=3]
df=df.loc[df['Have you felt frustrated by having your activities, major life events or opportunities affected by the virus? ']!=1]
df=df.loc[df['Do you feel like you have wasted your time during the lock down or have you ever felt pressurized by your peer’s accomplishments during the lock down?']!=0]
df.shape

(55, 39)

In [1032]:
X=df[[
       'How often do you use masks/hand sanitizers(per day)?',
       'Are you in a containment zone? ',
       'Have you ever felt afraid or anxious to go to hospital during this pandemic?',
       'Do you miss hanging out with people outside of your house?',
       
      ]]

In [1033]:
y=df['Level Of Anxiety ']

In [1040]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=0)

In [1041]:
regressor = DecisionTreeClassifier(random_state = 0) 
# fit the regressor with X and Y data 
regressor.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [1042]:
y_pred = regressor.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.4642857142857143

In [1043]:
regressor.feature_importances_

array([0.32132147, 0.10382606, 0.25917929, 0.31567318])

In [1044]:
y_test

727    0
443    0
567    0
307    1
80     0
18     0
429    0
640    1
749    0
400    2
28     1
76     0
343    1
250    0
406    1
772    0
536    1
58     0
106    1
323    0
497    1
786    0
168    0
810    2
454    1
157    1
33     0
375    0
Name: Level Of Anxiety , dtype: int64

In [1045]:
y_pred

array([0, 1, 2, 2, 0, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 2, 0,
       0, 1, 1, 1, 2, 1], dtype=int64)